Frame('frame',height=600, width=600)
goIn()

Button('alarm_on',text='Alarm aktivieren').grid(row=2, sticky='ew', column=6, pady=2)
Button('alarm_status',text='button', state='disabled', relief='flat').grid(row=3, sticky='ew', column=6, pady=2)
Button('close',text='Close').grid(columnspan=2, row=7, sticky='ew', column=1, pady=2)
Button('feueralarm',text='Feueralarm').grid(row=4, sticky='ew', column=6, pady=2)
Frame('frame',height=16, width=16).grid(row=0, column=7)
Frame('frame',height=16, width=16).grid(row=8)
Frame('frame',height=16, width=16).grid(row=0, column=5)
Label('label',text='Alarm inaktiv').grid(row=3, column=6)
Button('medical',text='Medical').grid(row=5, sticky='ew', column=6, pady=2)
Button('panik',text='Panik').grid(row=6, sticky='ew', column=6, pady=2)
Radiobutton('radiobutton_1',font='12', text='A', value=1).grid(row=2, padx=5, column=1)
Radiobutton('radiobutton_2',font='12', text='B', value=2).grid(row=2, column=2)
Radiobutton('radiobutton_3',font='12', text='C', value=3).grid(row=2, column=3)
Radiobutton('radiobutton_4',font='12', text='D', value=4).grid(row=2, column=4)
Button('service',text='Service').grid(row=7, sticky='ew', column=6, pady=2)
Text('text',height=5, width=30).grid(columnspan=4, rowspan=4, row=3, sticky='nesw', column=1)
Label('text_label1',font='12', text='Alarmzone').grid(columnspan=3, row=1, sticky='ew', padx=5, column=1, pady=5)

goOut()


widget('frame').pack(fill='both', expand=1)
