Button('close',**{'text': 'Close'}).grid(**{'column': '6', 'sticky': 'nesw', 'row': '23'})
Label('describe',**{'text': 'We will describe here:', 'bg': 'white', 'anchor': 'w'}).grid(**{'column': '1', 'sticky': 'nesw', 'columnspan': '2', 'row': '4'})
Label('describe_bold',**{'text': 'The additional options', 'font': 'TkDefaultFont 9 bold', 'bg': 'white', 'anchor': 'w'}).grid(**{'column': '3', 'sticky': 'nesw', 'columnspan': '4', 'row': '4'})
Message('lead_text',**{'text': 'The Config Options - menu Config ON - contain the normal config options of the widgets and additional ones.\n\nFor the normal options you will find buttons combined with listboxes, colorchooser or short help texts. Further information exists in the tkinter documentation. So these options will not be further discusssed here. The GuiDesigner let you try these options, so you may see, what they do.', 'width': '500', 'bg': 'white', 'anchor': 'w'}).grid(**{'column': '1', 'sticky': 'ew', 'columnspan': '6', 'row': '3'})
LinkLabel('link_link',**{'text': 'link option', 'font': 'TkFixedFont 9 bold underline', 'bg': 'white', 'link': 'guidesigner/HelpLinkOption.py', 'fg': 'blue', 'anchor': 'w'}).grid(**{'column': '4', 'sticky': 'nesw', 'columnspan': '3', 'row': '16'})
Message('myclass_code',**{'text': 'label_cat.meow()\nlabel_dog.bark()', 'font': 'TkFixedFont 9 bold', 'width': '500', 'bg': 'white', 'fg': 'blue', 'anchor': 'w'}).grid(**{'column': '1', 'sticky': 'nesw', 'columnspan': '6', 'row': '20'})
Message('myclass_explain',**{'text': "Therefore you may enter in myclass your class names, maybe 'Cat' and 'Dog'.And after you have defined these classes in your program, you may load the gui script by:\n\nload_script(filename,(Cat,Dog))\n\nThe class list may be a tuple or a list", 'width': '500', 'bg': 'white', 'anchor': 'w'}).grid(**{'column': '1', 'sticky': 'nesw', 'columnspan': '6', 'row': '21'})
Message('myclass_text',**{'text': "Normally a gui script is loaded in a program via function load_script(filename). And a button will be a button and a label a label. But this don't seem to be enough for everybody. Some persons like to have own classes. So one label should be a cat and shall meow and another widget a dog and shall bark and this should be possible:", 'width': '500', 'bg': 'white', 'anchor': 'w'}).grid(**{'column': '1', 'sticky': 'nesw', 'columnspan': '6', 'row': '19'})
Message('text_link',**{'text': 'For further information about link see:', 'width': '600', 'bg': 'white', 'anchor': 'w'}).grid(**{'column': '1', 'sticky': 'nesw', 'columnspan': '3', 'row': '16'})
Message('text_listbox',**{'text': "Listboxes don't have a text option in tkinter. But it's useful, if you can enter the content of a listbox already, when you design your GUI. So simply enter the content of a listbox as a text with newlines.", 'width': '500', 'bg': 'white', 'anchor': 'w'}).grid(**{'column': '1', 'sticky': 'nesw', 'columnspan': '6', 'row': '10'})
Message('text_mainwindow_options',**{'text': 'Besides the class and the name of widgets the GuiDesigner handles only two other types of information: config and layout\n\nSo these additional widget functions were integrated in the config options.', 'width': '500', 'bg': 'white', 'anchor': 'w'}).grid(**{'column': '1', 'sticky': 'ew', 'columnspan': '6', 'row': '7'})
Message('text_photoimage',**{'text': "Editing the entry 'image' in the config options didn't make sense. So we display instead an entry 'photoimage'.\n\nSimply enter the path for an image file with format gif, ppm or pgm. You may try 'introduction/start_image.gif'\n\nOther formats are also possible, if you adapt the interface file 'DynTkImage.py' to PIL or Pillows.\n\nBut don't forget, that this would work for you, but not for others, who don't have installed PIL or Pillows.\n", 'width': '500', 'bg': 'white', 'anchor': 'w'}).grid(**{'column': '1', 'sticky': 'nesw', 'columnspan': '6', 'row': '13'})
Label('title',**{'text': 'Config Options', 'font': 'TkDefaultFont 12 bold', 'fg': 'blue'}).grid(**{'column': '1', 'sticky': 'w', 'columnspan': '2', 'row': '1'})
Label('title_link',**{'text': 'link', 'font': 'TkDefaultFont 9 bold', 'bg': 'white', 'anchor': 'w'}).grid(**{'column': '1', 'sticky': 'nesw', 'columnspan': '6', 'row': '15'})
Label('title_listbox',**{'text': 'text for listboxes', 'font': 'TkDefaultFont 9 bold', 'bg': 'white', 'anchor': 'w'}).grid(**{'column': '1', 'sticky': 'nesw', 'columnspan': '6', 'row': '9'})
Label('title_mainwindow_options',**{'text': 'title and geometry', 'font': 'TkDefaultFont 9 bold', 'bg': 'white', 'anchor': 'w'}).grid(**{'column': '1', 'sticky': 'nesw', 'columnspan': '6', 'row': '6'})
Label('title_myclass',**{'text': 'myclass', 'font': 'TkDefaultFont 9 bold', 'bg': 'white', 'anchor': 'w', 'justify': 'left'}).grid(**{'column': '1', 'sticky': 'nesw', 'columnspan': '6', 'row': '18'})
Label('title_photoimage',**{'text': 'photoimage', 'font': 'TkDefaultFont 9 bold', 'bg': 'white', 'anchor': 'w', 'justify': 'left'}).grid(**{'column': '1', 'sticky': 'nesw', 'columnspan': '6', 'row': '12'})

### CODE ===================================================
def do_close(cont=container()):
    cont.destroy()

widget('close').do_command(do_close)
### ========================================================
