Toplevel('HelpPlaceForCode',**{'title': 'Right Place for Code', 'grid_cols': '(7, 75, 0, 0)', 'grid_multi_cols': '[7, (0, 10, 0, 0), (6, 10, 0, 0)]', 'grid_rows': '(9, 10, 0, 0)'})

Message('after_comment',**{'text': "We should find the comment enclosed in a marked CODE block, beginning with ### CODE = and ending with ### =\nThese comments are needed, so don't erase them. These comments must begin at the begin of the line. What is enclosed here, the GUI Designer will always load and save. When you load this file by the GUI Designer, such code blocks are stored within the GUI and will be written to the source file, when you save your GUI. So you may modify the GUI without loosing your added code.\n\nBut notice, there may only be one such code block for a container widget. If you would make a second one for the same container widget, one of them would be lost.", 'width': '430', 'bg': 'white', 'anchor': 'w'}).grid(**{'column': '1', 'sticky': 'nesw', 'columnspan': '5', 'row': '5'})
Button('close',**{'text': 'Close', 'bd': '2'}).grid(**{'column': '5', 'sticky': 'nesw', 'row': '7'})
Message('comment',**{'text': '### CODE ===================================================\n# PLACE for my code\n### ========================================================', 'font': 'TkFixedFont 9 bold', 'width': '430', 'bg': 'white', 'fg': 'red', 'anchor': 'w'}).grid(**{'column': '1', 'sticky': 'nesw', 'columnspan': '5', 'row': '4'})
Message('lead_text',**{'text': 'As already written, the right place for code is just at the end of the definition of the content of a container widget, just before goOut(). But not easy to find, if the GUI is complex and some subcontainers are between. But there is also an easy way to find the right place. This may be done via menu Special -> Expert Options -> Code. Bgefore we do this, we should make a backup of our work. Then we have to select the container widget and then we use this menu option.\n\nA window will be opened. And we could write code in it, which then will be executed. But better, we write only a comment like:\n\n# PLACE for my code\n\nThen we press OK, and save the GUI and may search for the comment in the saved source:', 'width': '430', 'bg': 'white', 'anchor': 'w'}).grid(**{'column': '1', 'sticky': 'nesw', 'columnspan': '5', 'row': '3'})
Label('title',**{'text': 'Right Place for Code', 'font': 'TkDefaultFont 12 bold', 'bg': 'white', 'fg': 'blue', 'anchor': 'w'}).grid(**{'column': '1', 'sticky': 'nesw', 'columnspan': '5', 'row': '1'})

### CODE ===================================================
widget('close').do_command(lambda cont = container(): cont.destroy())
### ========================================================
