NOLAYOUT = 0
PACKLAYOUT = 1
GRIDLAYOUT = 2
PLACELAYOUT = 4
PANELAYOUT = 8
TTKPANELAYOUT = 16
MENUITEMLAYOUT = 32
MENULAYOUT = 64
WINDOWLAYOUT = 128
PAGELAYOUT = 256

LAYOUTNEVER = 512
LAYOUTALL = LAYOUTNEVER-1
